/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.baker.View;

import com.baker.Requests.RequestGet;
import com.baker.Requests.RequestPost;
import com.baker.simpleExceptions.SimpleException;
import com.baker.utils.HardwareInfoGetter;
import com.baker.utils.TypesChangers;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Baker
 */
public class AllPanels extends javax.swing.JPanel {

    /**
     * Creates new form UserInfoPanel
     *
     * @param allUserData
     * @param authToken
     * @throws com.baker.simpleExceptions.SimpleException
     */
    public AllPanels() {
        HardwareInfoGetter hardware = new HardwareInfoGetter();

        initComponents();
        //Set Text Area
        pcInfoTextArea.setText(hardware.getSystemInfo());
        pcInfoTextArea.setEditable(false);

        // Set size and location
        setSize(584, 578);
        setLocation(0, 0);

        try {
            userStatsPanel();
        } catch (SimpleException e) {
            System.out.println("error " + e.getMessage());
        }

        System.out.println("Started!");

    }

    private void userStatsPanel() throws SimpleException {
        userInfoWriteOnLabels();

    }

    private void userInfoWriteOnLabels() throws SimpleException {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AllPanels = new com.baker.View.Components.MaterialTabbed();
        userInfoPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        OtherTitle1 = new javax.swing.JLabel();
        matchEditor = new javax.swing.JPanel();
        MainTitle = new javax.swing.JLabel();
        pcInfo = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        pcInfoTextArea = new javax.swing.JTextArea();
        MainTitle1 = new javax.swing.JLabel();

        AllPanels.setBackground(new java.awt.Color(62, 62, 62));
        AllPanels.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(155, 216, 184));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        OtherTitle1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        OtherTitle1.setText("COOL PANEL WITH BAR -->");

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OtherTitle1)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(OtherTitle1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AllPanels.addTab("panel1", userInfoPanel);

        matchEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ax(evt);
            }
        });

        MainTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        MainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitle.setText("PANEL 2");

        javax.swing.GroupLayout matchEditorLayout = new javax.swing.GroupLayout(matchEditor);
        matchEditor.setLayout(matchEditorLayout);
        matchEditorLayout.setHorizontalGroup(
            matchEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        matchEditorLayout.setVerticalGroup(
            matchEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matchEditorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(MainTitle)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        AllPanels.addTab("panel2", matchEditor);

        pcInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pcInfoax(evt);
            }
        });

        pcInfoTextArea.setColumns(20);
        pcInfoTextArea.setRows(5);
        ScrollPane.setViewportView(pcInfoTextArea);

        MainTitle1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        MainTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitle1.setText("Pc Info");

        javax.swing.GroupLayout pcInfoLayout = new javax.swing.GroupLayout(pcInfo);
        pcInfo.setLayout(pcInfoLayout);
        pcInfoLayout.setHorizontalGroup(
            pcInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addGroup(pcInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane)
                .addContainerGap())
        );
        pcInfoLayout.setVerticalGroup(
            pcInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcInfoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(MainTitle1)
                .addGap(18, 18, 18)
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        AllPanels.addTab("Información del Pc", pcInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AllPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AllPanels.getAccessibleContext().setAccessibleName("userInfo");
    }// </editor-fold>//GEN-END:initComponents

    private void ax(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ax
        // TODO add your handling code here:
    }//GEN-LAST:event_ax

    private void pcInfoax(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcInfoax
        // TODO add your handling code here:
    }//GEN-LAST:event_pcInfoax


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.baker.View.Components.MaterialTabbed AllPanels;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel MainTitle1;
    private javax.swing.JLabel OtherTitle1;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel matchEditor;
    private javax.swing.JPanel pcInfo;
    private javax.swing.JTextArea pcInfoTextArea;
    private javax.swing.JPanel userInfoPanel;
    // End of variables declaration//GEN-END:variables
}
